import { Product } from '@/types';

const img = (name: string) => `/products/${name}.jpg`;

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Quantum Sonic X1',
    price: 2499,
    category: 'Headphones',
    image: img('headphones'),
    images: [img('headphones'), img('earbuds')],
    description: 'Premium noise-cancelling headphones with adaptive audio and hand-finished metal hardware.',
    specs: {
      'Noise Cancellation': 'Adaptive ANC',
      'Battery Life': '60 hours',
      'Connectivity': 'Bluetooth 5.3, USB-C',
      'Driver Size': '40mm',
      'Weight': '245g',
      'Warranty': '3 years',
    },
    isLimited: true,
    stock: 15,
  },
  {
    id: '2',
    name: 'LunaSound Pro Speaker',
    price: 1899,
    category: 'Smart Speakers',
    image: img('audio-interface'),
    images: [img('audio-interface'), img('microphone')],
    description: 'High-fidelity smart speaker with voice control, warm acoustics, and sculpted aluminum trim.',
    specs: {
      'Audio Output': '360W Multi-driver',
      'Connectivity': 'WiFi 6, Bluetooth 5.2',
      'Voice Assistant': 'AI-powered',
      'Finish': 'Brushed Aluminum',
      'Dimensions': '200x200x150mm',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 32,
  },
  {
    id: '3',
    name: 'Titan Ultra Smartphone',
    price: 3299,
    category: 'Luxury Smartphones',
    image: img('smartphone'),
    images: [img('smartphone'), img('tablet')],
    description: 'Ultra-premium flagship smartphone with titanium frame and diamond-hard display glass.',
    specs: {
      'Processor': 'Snapdragon 9 Gen 3',
      'Display': '6.8" AMOLED 120Hz',
      'Storage': '1TB',
      'Camera': '200MP Main + 50MP Periscope',
      'Battery': '5500mAh 90W',
      'Warranty': '3 years',
    },
    isLimited: true,
    stock: 8,
  },
  {
    id: '4',
    name: 'Prism Ultra Tablet',
    price: 1799,
    category: 'Computing',
    image: img('tablet'),
    images: [img('tablet'), img('laptop')],
    description: 'Premium tablet with fluid display, studio-grade color, and precision stylus support.',
    specs: {
      'Display': '12.9" Retina LCD',
      'Processor': 'A18 Bionic',
      'Storage': '512GB',
      'Stylus Support': 'Precision Stylus Pro',
      'Weight': '485g',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 24,
  },
  {
    id: '5',
    name: 'Quantum Earbuds Pro',
    price: 899,
    category: 'Headphones',
    image: img('earbuds'),
    images: [img('earbuds'), img('headphones')],
    description: 'True wireless earbuds with personalized sound profiles and active noise cancellation.',
    specs: {
      'Drivers': '10mm Dual',
      'Battery': '8 hours (32 with case)',
      'Charging': 'Wireless charging case',
      'Noise Cancellation': 'ANC 2.0',
      'Weight': '4.2g per bud',
      'Warranty': '2 years',
    },
    isLimited: true,
    stock: 50,
  },
  {
    id: '6',
    name: 'Nexus Air Fitness Pro',
    price: 1299,
    category: 'Wearables',
    image: img('smartwatch'),
    images: [img('smartwatch'), img('vr-headset')],
    description: 'Advanced fitness tracker with medical-grade health sensors and adaptive coaching.',
    specs: {
      'Sensors': 'Heart rate, SpO2, ECG',
      'Battery Life': '7 days',
      'Water Resistance': '5ATM',
      'Display': '1.4" AMOLED',
      'Weight': '28g',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 40,
  },
  {
    id: '7',
    name: 'Luna Vision 4K Webcam',
    price: 599,
    category: 'Computing',
    image: img('webcam'),
    images: [img('webcam'), img('camera')],
    description: 'Professional 4K webcam with AI auto-focus and studio lighting correction.',
    specs: {
      'Resolution': '4K 60fps',
      'Sensor': '1" CMOS',
      'Focus': 'AI Auto-focus',
      'Microphone': 'Dual directional',
      'Mount': 'Magnetic',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 28,
  },
  {
    id: '8',
    name: 'Titan Charge Atelier',
    price: 349,
    category: 'Accessories',
    image: img('charger'),
    images: [img('charger'), img('dock')],
    description: 'Ultra-fast GaN charging kit with woven cables and multi-device power routing.',
    specs: {
      'Output': '240W Max',
      'Ports': '4x USB-C',
      'Technology': 'GaN 5.0',
      'Efficiency': '95%',
      'Weight': '185g',
      'Warranty': '2 years',
    },
    isLimited: true,
    stock: 60,
  },
  {
    id: '9',
    name: 'Aurora Studio Monitor',
    price: 2199,
    category: 'Computing',
    image: img('monitor'),
    images: [img('monitor'), img('laptop')],
    description: '4K creative monitor with 144Hz refresh, calibrated color, and quantum dot contrast.',
    specs: {
      'Resolution': '4K (3840x2160)',
      'Refresh Rate': '144Hz',
      'Response Time': '1ms',
      'Panel': 'Quantum Dot',
      'Size': '32 inches',
      'Warranty': '3 years',
    },
    isLimited: false,
    stock: 12,
  },
  {
    id: '10',
    name: 'Zenith Audio Interface',
    price: 1499,
    category: 'Limited Edition Audio',
    image: img('audio-interface'),
    images: [img('audio-interface'), img('microphone')],
    description: 'Professional audio interface with 8 channels and studio-grade preamps. Serial numbered.',
    specs: {
      'Channels': '8 In / 8 Out',
      'Preamps': 'Neve-style compression',
      'Connectivity': 'Thunderbolt 3, USB-C',
      'Latency': '< 1ms',
      'Edition': 'Limited #001-100',
      'Warranty': '5 years',
    },
    isLimited: true,
    stock: 3,
  },
  {
    id: '11',
    name: 'Harmony Wireless Microphone',
    price: 799,
    category: 'Limited Edition Audio',
    image: img('microphone'),
    images: [img('microphone'), img('audio-interface')],
    description: 'Wireless condenser microphone with stable frequency response and broadcast clarity.',
    specs: {
      'Type': 'Condenser Wireless',
      'Frequency': '20Hz - 20kHz',
      'Range': '50m unobstructed',
      'Battery': '12 hours',
      'Noise Floor': '-128dB',
      'Warranty': '2 years',
    },
    isLimited: true,
    stock: 7,
  },
  {
    id: '12',
    name: 'Nexus Smart Watch Elite',
    price: 1599,
    category: 'Wearables',
    image: img('smartwatch'),
    images: [img('smartwatch'), img('smartphone')],
    description: 'Premium smartwatch with sapphire crystal and gold-toned titanium case.',
    specs: {
      'Display': '1.5" AMOLED',
      'Processor': 'Dual-core 2.5GHz',
      'Storage': '16GB',
      'Battery': '3 days',
      'Material': 'Titanium + Sapphire',
      'Warranty': '3 years',
    },
    isLimited: true,
    stock: 10,
  },
  {
    id: '13',
    name: 'Prism Portable SSD',
    price: 449,
    category: 'Accessories',
    image: img('ssd'),
    images: [img('ssd'), img('dock')],
    description: '2TB portable SSD with hardware encryption and ultra-fast transfer speeds.',
    specs: {
      'Capacity': '2TB',
      'Speed': '1050MB/s read/write',
      'Encryption': '256-bit AES',
      'Weight': '92g',
      'Durability': 'IP67 Rated',
      'Warranty': '5 years',
    },
    isLimited: false,
    stock: 45,
  },
  {
    id: '14',
    name: 'Luna Portable Projector',
    price: 1299,
    category: 'Home Cinema',
    image: img('projector'),
    images: [img('projector'), img('console')],
    description: 'Compact 4K projector with 2000 ANSI lumens and smart wireless casting.',
    specs: {
      'Resolution': 'Native 1080p, 4K support',
      'Brightness': '2000 ANSI lumens',
      'Contrast': '100000:1',
      'Weight': '820g',
      'Connectivity': 'WiFi 6, Bluetooth',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 18,
  },
  {
    id: '15',
    name: 'Quantum Keyboard Pro',
    price: 349,
    category: 'Computing',
    image: img('keyboard'),
    images: [img('keyboard'), img('monitor')],
    description: 'Mechanical keyboard with programmable lighting and machined aluminum chassis.',
    specs: {
      'Switches': 'Quantum Mechanical',
      'Layout': 'Full-size 104 key',
      'Lighting': 'Per-key RGB',
      'Connectivity': 'Wireless 2.4GHz',
      'Weight': '945g',
      'Warranty': '3 years',
    },
    isLimited: false,
    stock: 55,
  },
  {
    id: '16',
    name: 'Aperture Mirrorless Kit',
    price: 2899,
    category: 'Cameras',
    image: img('camera'),
    images: [img('camera'), img('webcam')],
    description: 'Compact mirrorless camera kit with fast glass, low-light clarity, and cinematic color.',
    specs: {
      'Sensor': 'Full-frame CMOS',
      'Video': '6K ProRes',
      'Stabilization': '5-axis IBIS',
      'Lens Mount': 'L-Mount',
      'Body': 'Magnesium alloy',
      'Warranty': '3 years',
    },
    isLimited: true,
    stock: 9,
  },
  {
    id: '17',
    name: 'Orbit Cinema Drone',
    price: 2399,
    category: 'Cameras',
    image: img('drone'),
    images: [img('drone'), img('camera')],
    description: 'Foldable camera drone with obstacle sensing, stabilized 4K video, and premium controller.',
    specs: {
      'Camera': '4K HDR',
      'Flight Time': '42 minutes',
      'Range': '12km',
      'Avoidance': 'Omnidirectional',
      'Weight': '720g',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 14,
  },
  {
    id: '18',
    name: 'Nova Gaming Console',
    price: 699,
    category: 'Gaming',
    image: img('console'),
    images: [img('console'), img('monitor')],
    description: 'Next-gen gaming console with fast storage, quiet cooling, and cinematic performance.',
    specs: {
      'Storage': '2TB NVMe',
      'Output': '4K 120Hz',
      'Audio': 'Spatial 3D',
      'Controller': 'Haptic wireless',
      'Cooling': 'Vapor chamber',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 34,
  },
  {
    id: '19',
    name: 'Atlas WiFi 7 Router',
    price: 549,
    category: 'Networking',
    image: img('router'),
    images: [img('router'), img('dock')],
    description: 'Tri-band WiFi 7 router with mesh expansion, low-latency routing, and elegant enclosure.',
    specs: {
      'Wireless': 'WiFi 7 tri-band',
      'Coverage': '4,500 sq ft',
      'Ports': '2.5GbE x4',
      'Security': 'WPA3 + VPN',
      'Mesh': 'Expandable',
      'Warranty': '3 years',
    },
    isLimited: false,
    stock: 27,
  },
  {
    id: '20',
    name: 'Element USB-C Dock',
    price: 399,
    category: 'Accessories',
    image: img('dock'),
    images: [img('dock'), img('laptop')],
    description: 'Desktop USB-C dock with dual display support, high-speed IO, and premium metal finish.',
    specs: {
      'Displays': 'Dual 4K',
      'Power': '100W passthrough',
      'Ports': '12 total',
      'Ethernet': '2.5GbE',
      'Material': 'Anodized aluminum',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 42,
  },
  {
    id: '21',
    name: 'Halo Immersive Headset',
    price: 1199,
    category: 'Gaming',
    image: img('vr-headset'),
    images: [img('vr-headset'), img('console')],
    description: 'Immersive mixed-reality headset with high-resolution optics and balanced comfort.',
    specs: {
      'Display': 'Micro-OLED',
      'Tracking': 'Inside-out 6DoF',
      'Audio': 'Spatial open-ear',
      'Battery': '3 hours',
      'Weight': '515g',
      'Warranty': '2 years',
    },
    isLimited: true,
    stock: 11,
  },
  {
    id: '22',
    name: 'Solstice Pro Laptop',
    price: 2799,
    category: 'Computing',
    image: img('laptop'),
    images: [img('laptop'), img('keyboard')],
    description: 'Thin performance laptop with a color-accurate display and all-day battery life.',
    specs: {
      'Processor': '12-core Pro silicon',
      'Display': '14.5" OLED',
      'Memory': '32GB',
      'Storage': '2TB',
      'Battery': '18 hours',
      'Warranty': '3 years',
    },
    isLimited: false,
    stock: 19,
  },
  {
    id: '23',
    name: 'Obsidian Studio Bundle',
    price: 2199,
    category: 'Limited Edition Audio',
    image: img('microphone'),
    images: [img('microphone'), img('headphones')],
    description: 'Limited recording bundle with microphone, headphones, interface, and desk accessories.',
    specs: {
      'Bundle': 'Mic + interface + headphones',
      'Sample Rate': '192kHz',
      'Finish': 'Matte black',
      'Edition': 'Limited #001-250',
      'Case': 'Hard-shell travel case',
      'Warranty': '5 years',
    },
    isLimited: true,
    stock: 6,
  },
  {
    id: '24',
    name: 'Luna Desk Command Kit',
    price: 999,
    category: 'Accessories',
    image: img('dock'),
    images: [img('dock'), img('keyboard')],
    description: 'Premium desk setup kit with dock, charger, keyboard, and braided cable system.',
    specs: {
      'Dock': '12-port USB-C',
      'Keyboard': 'Low-profile mechanical',
      'Charging': '140W GaN',
      'Cables': 'Braided set',
      'Finish': 'Graphite',
      'Warranty': '2 years',
    },
    isLimited: false,
    stock: 25,
  },
];

export const categories = [
  'All Products',
  'Headphones',
  'Smart Speakers',
  'Luxury Smartphones',
  'Computing',
  'Wearables',
  'Accessories',
  'Cameras',
  'Gaming',
  'Networking',
  'Home Cinema',
  'Limited Edition Audio',
];

export const priceRanges = [
  { label: 'Under $500', min: 0, max: 500 },
  { label: '$500 - $1000', min: 500, max: 1000 },
  { label: '$1000 - $2000', min: 1000, max: 2000 },
  { label: '$2000+', min: 2000, max: Infinity },
];
